import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout'; // Import the Layout component
import SidebarMenu from '../components/SidebarMenu';
import styles from '../styles/Home.module.css';

function About() {
  const [language, setLanguage] = useState('english'); // Default language is English

  // Function to toggle between English and French
  const toggleLanguage = () => {
    setLanguage(language === 'english' ? 'french' : 'english');
  };

  // Define content for both English and French
  const content = {
    english: {
      title: "Alexandre Bailey-Proulx's Portfolio - About",
      description: 'Generated by Alexandre Bailey-Proulx',
      aboutMe: {
        heading: 'About Me:',
        intro: 'Hello, my name is Alexandre Bailey-Proulx. I have always had a deep passion for creating video games and software. My goal is to become a software developer, and I have studied at La Cité College in Ottawa, where I earned a Diploma in Computer Programming.',
        skills: 'I have proficiency in several programming languages, including C#, Java, HTML, CSS, as well as knowledge in networking and databases.',
        qualities: 'I am an organized and punctual individual with great attention to detail. I am also perfectly bilingual in English and French. I\'m a huge fan of video games of all genres, and I hope to collaborate with like-minded individuals on ambitious projects.',
      },
      buttonLabel: 'Switch to French',
    },
    french: {
      title: 'Portefolio d\'Alexandre Bailey-Proulx - À propos',
      description: 'Généré par Alexandre Bailey-Proulx',
      aboutMe: {
        heading: 'À propos de moi :',
        intro: 'Bonjour, je m\'appelle Alexandre Bailey-Proulx. J\'ai toujours eu une grande passion pour la création de jeux vidéo et de logiciels. Mon objectif est de devenir un développeur de logiciels, et j\'ai étudié au Collège La Cité à Ottawa, où j\'ai obtenu un diplôme en programmation informatique.',
        skills: 'Je maîtrise plusieurs langages de programmation, dont le C#, Java, HTML, CSS, ainsi que des connaissances en réseautique et en bases de données.',
        qualities: 'Je suis une personne bien organisée et ponctuelle, avec une grande attention aux détails. Je suis également parfaitement bilingue en anglais et en français. Je suis un grand fan de jeux vidéo de tous genres, et j\'espère collaborer avec des personnes partageant les mêmes ambitions sur des projets ambitieux.',
      },
      buttonLabel: 'Switch to English',
    },
  };

  const currentContent = content[language]; // Get content based on the selected language

  return (
    <Layout> {/* Wrap the content in a Layout component */}
      <div className={styles.centeredContainer}>
        <SidebarMenu />
        <div className={styles.flexGrow}>
          <Head>
            <title>{currentContent.title}</title> {/* Set the page title */}
            <meta name="description" content={currentContent.description} />
            <meta property="og:title" content={currentContent.title} />
            <meta property="og:description" content={currentContent.description} />
            <meta property="og:image" content={`${process.env.NEXT_PUBLIC_BASE_URL}/images/Me.jpg`} />
          </Head>
          <div className={styles.centerScreen}>
            <button onClick={toggleLanguage} className={styles.languageButton}>
              {currentContent.buttonLabel}
            </button>
            <h1 className={styles.titre}>{currentContent.aboutMe.heading}</h1>
            <div className={styles.centeredText}>
              <p className={styles.sousTitre}>{currentContent.aboutMe.intro}</p>
              <p className={styles.sousTitre}>{currentContent.aboutMe.skills}</p>
              <p className={styles.sousTitre}>{currentContent.aboutMe.qualities}</p>
            </div>
            <Image className={styles.image} src="/images/Me.jpg" alt="A picture of my face" width={200} height={200} />
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default About;
