import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout'; // Import the Layout component
import SidebarMenu from '../components/SidebarMenu';
import styles from '../styles/Home.module.css';

function Home() {
  return (
    <Layout> {/* Wrap the content in a Layout component */}
      <div className="flex">
        <SidebarMenu />
        <div className="flex-grow">
          <Head>
            <title>Portefolio Alexandre Bailey-Proulx Accueil</title> {/* Set the page title */}
         </Head>
          <div className={styles.centerScreen}>
            {/* Display a welcome message in both languages */}
            <h1 className={styles.titre}>Bienvenue sur le Portefolio D&apos;Alexandre </h1>
            <h1 className={styles.titre}>Welcome to Alexandre&apos;s Portefolio</h1>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default Home;

// Metadata for SEO purposes
Home.metadata = {
  title: 'Portfolio', // Set the page title for metadata
  description: 'Generated by Alexandre Bailey-Proulx', // Set a description for metadata
};
