import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout';
import SidebarMenu from '../components/SidebarMenu';
import styles from '../styles/Home.module.css';

function Home() {
  return (
    <Layout>
      <div className="flex">
        <SidebarMenu />
        <div className="flex-grow">
          <Head>
            <title>Portefolio Alexandre Bailey-Proulx Accueil</title>
         </Head>
          <div className={styles.centerScreen}>
           <h1 className={styles.titre}>Bienvenue sur mon Portefolio</h1>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default Home;

Home.metadata = {
  title: 'Portfolio',
  description: 'Generated by Alexandre Bailey-Proulx',
};
